version: '3'
services:
  statistics:
    container_name: statistics
    build: .
    image: statistics
    volumes:
      - database:/home/app/visitstatistics/database
volumes:
  database: { }

# Uses external network with routing
networks:
  default:
    external:
      name: production